### ISSUE TITLE
Crear página para Valeria ♥

### ISSUE THREAD

**Issue by ReyesRRV** [ReyesRRV/Aprendamos#1]
Raul esta completamente enamorado de Valeria, y quiere hacerle una página con sus mejores fotos. 

1- Tiene que contener fotos no porno de Valeria.
2- No puede ser parecida a OnlyFans.
3- Debe poder cambiar el tamaño de las fotos. 
4- No tiene que ser página inicial. 

Además, debe ser realizado unicamente con HTML

**Comment by Oorochimaru** [comment]
holi
